base: /Level1/
description: A Demo of the League Curriculum websites
head:
- - meta
  - content: '#F37121'
    name: theme-color
- - meta
  - content: true
    name: apple-mobile-web-app-capable
- - meta
  - content: black
    name: apple-mobile-web-app-status-bar-style
- - link
  - href: https://www.jointheleague.org/wp-content/uploads/2022/06/favicon-32x32-1.png
    rel: shortcut icon
    type: image/x-icon
plugins:
- '@vuepress/plugin-back-to-top'
- '@vuepress/plugin-medium-zoom'
themeConfig:
  displayAllHeaders: false
  docsDir: ''
  editLinkText: ''
  editLinks: false
  lastUpdated: false
  logo: /assets/Flag.png
  nav:
  - link: /about/
    text: About
  - link: https://jointheleague.org
    text: The LEAGUE
  repo: ''
  sidebar:
  - path: /
    title: Introduction
  - children:
    - path: /lessons/Module0/01_methods/
      title: 01 Methods 1 Houses
    - path: /lessons/Module0/02_return_types/
      title: 02 Return Types 1 Finish Line
    - path: /lessons/Module0/03_gui_with_help/
      title: 03 Gui With Help 1 My First Swing Gui
    - path: /lessons/Module0/04_gui_from_scratch/
      title: 04 Gui From Scratch 1 Fortune Cookie
    collapsable: false
    title: Module0
  - children:
    - path: /lessons/Module1/01_asteroids/
      title: 01 Asteroids
    - path: /lessons/Module1/02_race_car/
      title: 02 Race Car
    - path: /lessons/Module1/03_cat/
      title: 03 Cat
    - path: /lessons/Module1/04_harry_potter/
      title: 04 Harry Potter
    - path: /lessons/Module1/05_popcorn/
      title: 05 Popcorn
    - path: /lessons/Module1/06_vault/
      title: 06 Vault
    - path: /lessons/Module1/07_duck/
      title: 07 Duck
    - path: /lessons/Module1/08_SolarSystem/
      title: 08 Solarsystem
    - path: /lessons/Module1/09_HungryHungryHippos/
      title: 09 Hungryhungryhippos
    - path: /lessons/Module1/10_turf_war/
      title: 10 Turf War
    - path: /lessons/Module1/11_binary_converter/
      title: 11 Binary Converter
    collapsable: false
    title: Module1
  - children:
    - path: /lessons/Module2/01_sea_creature/
      title: 01 Sea Creature
    - path: /lessons/Module2/02_smurf/
      title: 02 Smurf
    - path: /lessons/Module2/03_tea_maker/
      title: 03 Tea Maker
    - path: /lessons/Module2/04_backpack/
      title: 04 Backpack
    - path: /lessons/Module2/99_extra/
      title: 99 Extra
    collapsable: false
    title: Module2
  - children:
    - path: /lessons/Module3/01_intro_to_static/
      title: 01 Intro To Static
    - path: /lessons/Module3/02_static_smiley_blues/
      title: 02 Static Smiley Blues
    - path: /lessons/Module3/04_netflix/
      title: 04 Netflix
    - path: /lessons/Module3/05_cow_timer/
      title: 05 Cow Timer
    - path: /lessons/Module3/06_frogger/
      title: 06 Frogger
    - path: /lessons/Module3/99_extra/
      title: 99 Extra 04 Gridworld
    collapsable: false
    title: Module3
  - children:
    - path: /lessons/Module4/01_chuckle_clicker/
      title: 01 Chuckle Clicker
    - path: /lessons/Module4/02_jeopardy/
      title: 02 Jeopardy
    - path: /lessons/Module4/03_typing_tutor/
      title: 03 Typing Tutor
    - path: /lessons/Module4/04_book_of_illusions/
      title: 04 Book Of Illusions
    - path: /lessons/Module4/05_fortune_teller/
      title: 05 Fortune Teller
    - path: /lessons/Module4/06_calculator/
      title: 06 Calculator
    - path: /lessons/Module4/07_tv_show_episode_info/
      title: 07 Tv Show Episode Info
    - path: /lessons/Module4/08_pig_latin/
      title: 08 Pig Latin
    - path: /lessons/Module4/09_whack_a_mole/
      title: 09 Whack A Mole
    - path: /lessons/Module4/10_slot_machine/
      title: 10 Slot Machine
    - path: /lessons/Module4/11_lights_out/
      title: 11 Lights Out
    - path: /lessons/Module4/12_online_practice_quiz/
      title: 12 Online Practice Quiz
    - path: /lessons/Module4/99_extra/
      title: 99 Extra
    collapsable: false
    title: Module4
title: League Demo
